### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by joshbackstein** [fcoury/kbpcb#1]
I think this is an awesome tool, and I'm really glad you've put it up on GitHub, but not having a license kind of puts people in a weird spot if they want to make contributions to it or continue development if you ever decide you don't want to work on it anymore.

Are you considering making this code available under an open source license at some point?

**Comment by fcoury** [comment]
License added :)

**Comment by joshbackstein** [comment]
Awesome! Quick response! Thanks!
